namespace: amitgujar0

name: azure_resources_custom

version: 1.0.2

readme: README.md

authors:
  - Amit Gujar amithero3342@gmail.com

description: your collection description

license:
  - MIT

tags:
  - azure
  - virtual_machine
  - vm
  - linux
  - cloud

dependencies: {}

repository: http://github.com/AmitGujar/myplaybooks

documentation: http://github.com/AmitGujar/myplaybooks/wiki

homepage: http://github.com/AmitGujar/myplaybooks

issues: http://github.com/AmitGujar/myplaybooks/issue/

build_ignore:
  - secret.txt
